runtime: python39
env: standard
entrypoint: gunicorn -b :$PORT main:app
service: default

instance_class: F2

automatic_scaling:
  min_instances: 10
  max_instances: 15

service_account: assignment-1-424613@appspot.gserviceaccount.com

handlers:
  - url: /.*
    script: auto
